# ------------------------ OS COMPATIBILITY (where i try and it's work) -------------------------
# OS: Ubuntu 18 - 20 
# ------------------------ OS COMPATIBILITY (where i try and it's work) -------------------------

- name : Install VSCode server
  shell : curl -fsSL https://code-server.dev/install.sh | sh
  tags : 
    - vscode
- name : Create the folder for the config
  file :
    path : /root/.config/code-server
    state : directory
  tags :
    - vscode
- name : Replace the default config.yaml
  copy :
    src : "{{ vscode_config_path }}"
    dest : /root/.config/code-server/config.yaml
  tags :
    - vscode
- name : Create the folder for the settings
  file :
    path : /root/.local/share/code-server/User
    state : directory
  tags :
    - vscode
- name : Replace the default settings.json
  copy :
    src : "{{ vscode_settings_path }}"
    dest : /root/.local/share/code-server/User/settings.json
  tags :
    - vscode
- name : Install the extension
  shell : code-server --install-extension pkief.material-icon-theme
  tags :
    - vscode

# ------------------------ LAST STEP -------------------------
# Need in the CMD commande in dockerfile to launch the server in background.
# CMD bash -c "code-server &"
# ------------------------ LAST STEP -------------------------