# ------------------------ OS COMPATIBILITY (where i try and it's work) -------------------------
# OS: Ubuntu 24  
# ------------------------ OS COMPATIBILITY (where i try and it's work) -------------------------

# ------------------------ Description -------------------------
#
# Config Flux 1 DEV models ( DoubleCLIP + VAE + DIFFUSERS MODEL )
#
# ------------------------ Description -------------------------
- name: Vérifier et copier les fichiers pour flux 1 DEV
  vars:
    files: 
      - { name: flux1-dev, dest_comfyui: unet }
      - { name: ae, dest_comfyui: vae }
      - { name: clip_l, dest_comfyui: clip }
      - { name: t5xxl_fp8_e4m3fn, dest_comfyui: clip }
      - { name: t5xxl_fp16, dest_comfyui: clip }
  tags:
    - config_models
  block:
    - name: Vérifier si les fichiers existent
      ansible.builtin.stat:
        path: "{{ src_download_path }}/{{ item.name }}.safetensors"
      register: stat_results
      loop: "{{ files }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Copier les fichiers s'ils existent
      ansible.builtin.copy:
        src: "{{ src_download_path }}/{{ item.item.name }}.safetensors"
        dest: "{{ confyui_path }}/models/{{ item.item.dest_comfyui }}/{{ item.item.name }}.safetensors"
      when: item.stat.exists
      loop: "{{ stat_results.results }}"
      loop_control:
        label: "{{ item.item.name }}"