# ------------------------ OS COMPATIBILITY (where i try and it's work) -------------------------
# OS: Ubuntu 24  
# ------------------------ OS COMPATIBILITY (where i try and it's work) -------------------------


- name: Install all submodules with git
  ansible.builtin.shell:
    cmd: "git submodule update --init --recursive"
  tags:
    - install_plugins

- name: Check if the requirements.txt file exists
  ansible.builtin.stat:
    path: "/app/src/ComfyUI/custom_nodes/{{ item.name }}/requirements.txt"
  loop:
    - "{{ plugins }}"
  loop_control:
    loop_var: item
  register: requirements_files

- name: Install all python dependencies
  ansible.builtin.pip:
    requirements: "/app/src/ComfyUI/custom_nodes/{{ item.name }}/requirements.txt"
    executable: /app/src/venv/bin/pip
  loop:
    - "{{ plugins }}"
  loop_control:
    loop_var: item
  when: requirements_files.results[loop.index0].stat.exists
  tags:
    - install_plugins