# ------------------------ OS COMPATIBILITY (where i try and it's work) -------------------------
# OS: Ubuntu 24  
# ------------------------ OS COMPATIBILITY (where i try and it's work) -------------------------


- name: Install all submodules with git
  ansible.builtin.shell:
    cmd: "git submodule update --init --recursive"
  tags:
    - kohyass

- name: Install Kohya_ss
  ansible.builtin.command:
    cmd: "./setup-runpod.sh"
    chdir: /app/src/kohya_ss
  tags:
    - kohyass