# ------------------------ OS COMPATIBILITY (where i try and it's work) -------------------------
# OS: Ubuntu 24  
# ------------------------ OS COMPATIBILITY (where i try and it's work) -------------------------

- name: Install FLUX 1 DEV models
  ansible.builtin.get_url:
    url: https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/flux1-dev.safetensors
    dest: /app/src/ComfyUI/models/checkpoints/flux1-dev.safetensors
    force: no
    headers:
      Authorization : "Bearer {{ huggingface_token }}"
  tags:
    - install_models