# ------------------------ OS COMPATIBILITY (where i try and it's work) -------------------------
# OS: Ubuntu 24  
# ------------------------ OS COMPATIBILITY (where i try and it's work) -------------------------


# ------------------------ Description -------------------------
#
# Install Flux 1 DEV models ( DoucleCLIP + VAE + DIFFUSERS MODEL )
#
# ------------------------ Description -------------------------
- name: Install FLUX 1 DEV MODEL
  vars:
    flux_dev:
      - { name: flux1-dev, url: "https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/flux1-dev.safetensors" }
      - { name: ae, url: "https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/ae.safetensors" }
      - { name: clip_l, url: "https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/clip_l.safetensors" }
      - { name: t5xxl_fp8_e4m3fn, url: "https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/t5xxl_fp8_e4m3fn.safetensors" }
      - { name: t5xxl_fp16, url: "https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/t5xxl_fp16.safetensors" }
  tags:
    - install_models
  block:
    - name: Install {{ item.name }} MODEL
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ dest_download_path }}/{{ item.name }}.safetensors"
        force: no
        headers:
          Authorization : "Bearer {{ huggingface_token }}"
      loop: "{{ flux_dev }}"
      loop_control:
        label: "{{ item.name }}"