name: Docker Image CI

on:
  push:

jobs:
  push-docker:
    runs-on: [self-hosted, macOS, ARM64]
    environment: 
      name: Docker
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Copy repository contents
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set IMAGE_NAME
        run: |
          echo "IMAGE_NAME=wglint/maincargo:${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV

      - name: Check environment
        run: |
          echo "Docker Image Name: $IMAGE_NAME"
          echo "Docker Username: ${{ env.DOCKER_USERNAME }}"
          echo "Docker Password: ${{ env.DOCKER_PASSWORD }}"
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}
